/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project0;

public class App 
{
    public static void main(String[] args) 
    {
        ShoppingList shoppingList = new ShoppingList();
        ListController controller = new ListController(shoppingList);

        boolean continueWriting = true;
        while(continueWriting)
        {
            controller.displayInitialMessage();
            continueWriting = controller.menu();

            if(continueWriting)
            {
                System.out.println("-------------------------------------------");
            }
        }
    }
}
